### ISSUE TITLE
Start with viw

### ISSUE THREAD

**Issue by janbaer** [gorkunov/smartpairs.vim#10]
I just wanted to use smart-pairs for the first time and my cursor was inside of a word. So I wanted to use smart-pairs instead of typing **viw**. But it was selecting automatically everything inside the {}. This would be my second expectation when I would type v for the next type. Would it break anything, when the first action would be **viw**? Just a suggestion...

**Comment by gorkunov** [comment]
I think that maybe a cool option. I'll add it (can't say when :).

**Comment by gorkunov** [comment]
@janbaer I just found that this option is already implemented. Just set `let g:smartpairs_start_from_word = 1` in your vim config.

**Comment by janbaer** [comment]
Works great! Thank you!

**Comment by gorkunov** [comment]
@janbaer just make your note: I updated master with hot fix for word selection...
