### ISSUE TITLE
Conflicts with vim-multiple-cursors plugin

### ISSUE THREAD

**Issue by tecfu** [gorkunov/smartpairs.vim#8]
Conflicts with vim-multiple-cursors: That plugin cannot append when smartpairs.vim is enabled, but keymapping doesn't seem to be the cause.

**Comment by gorkunov** [comment]
I played with vim-multiple-cursors a week and it works great. I have no problem both plugins.

@tecfu Are you sure that problem is in smartpairs?

**Comment by tecfu** [comment]
I apologize for this, I re-tested and had no issues. Either there was a conflict in my .vimrc or the issue was self-resolved by upgrading to Vim 8. 

Probably just my mistake. Sorry to waste your time.

**Comment by tecfu** [comment]
Closing.
